export const DEPARTEMENTS = [
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "01", "departementName": "Ain" },
  { "regionKey": "hauts-de-france", "region": "Hauts-de-France", "departementNumber": "02", "departementName": "Aisne" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "03", "departementName": "Allier" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "04", "departementName": "Alpes-de-Haute-Provence" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "05", "departementName": "Hautes-Alpes" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "06", "departementName": "Alpes-Maritimes" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "07", "departementName": "Ardèche" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "08", "departementName": "Ardennes" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "09", "departementName": "Ariège" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "10", "departementName": "Aube" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "11", "departementName": "Aude" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "12", "departementName": "Aveyron" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "13", "departementName": "Bouches-du-Rhône" },
  { "regionKey": "normandie", "region": "Normandie", "departementNumber": "14", "departementName": "Calvados" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "15", "departementName": "Cantal" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "16", "departementName": "Charente" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "17", "departementName": "Charente-Maritime" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "18", "departementName": "Cher" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "19", "departementName": "Corrèze" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "21", "departementName": "Côte-d'Or" },
  { "regionKey": "bretagne", "region": "Bretagne", "departementNumber": "22", "departementName": "Côtes-d'Armor" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "23", "departementName": "Creuse" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "24", "departementName": "Dordogne" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "25", "departementName": "Doubs" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "26", "departementName": "Drôme" },
  { "regionKey": "normandie", "region": "Normandie", "departementNumber": "27", "departementName": "Eure" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "28", "departementName": "Eure-et-Loir" },
  { "regionKey": "bretagne", "region": "Bretagne", "departementNumber": "29", "departementName": "Finistère" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "30", "departementName": "Gard" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "31", "departementName": "Haute-Garonne" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "32", "departementName": "Gers" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "33", "departementName": "Gironde" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "34", "departementName": "Hérault" },
  { "regionKey": "bretagne", "region": "Bretagne", "departementNumber": "35", "departementName": "Ille-et-Vilaine" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "36", "departementName": "Indre" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "37", "departementName": "Indre-et-Loire" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "38", "departementName": "Isère" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "39", "departementName": "Jura" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "40", "departementName": "Landes" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "41", "departementName": "Loir-et-Cher" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "42", "departementName": "Loire" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "43", "departementName": "Haute-Loire" },
  { "regionKey": "pays-de-la-loire", "region": "Pays de la Loire", "departementNumber": "44", "departementName": "Loire-Atlantique" },
  { "regionKey": "centre-val-de-loire", "region": "Centre-Val de Loire", "departementNumber": "45", "departementName": "Loiret" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "46", "departementName": "Lot" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "47", "departementName": "Lot-et-Garonne" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "48", "departementName": "Lozère" },
  { "regionKey": "pays-de-la-loire", "region": "Pays de la Loire", "departementNumber": "49", "departementName": "Maine-et-Loire" },
  { "regionKey": "normandie", "region": "Normandie", "departementNumber": "50", "departementName": "Manche" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "51", "departementName": "Marne" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "52", "departementName": "Haute-Marne" },
  { "regionKey": "pays-de-la-loire", "region": "Pays de la Loire", "departementNumber": "53", "departementName": "Mayenne" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "54", "departementName": "Meurthe-et-Moselle" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "55", "departementName": "Meuse" },
  { "regionKey": "bretagne", "region": "Bretagne", "departementNumber": "56", "departementName": "Morbihan" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "57", "departementName": "Moselle" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "58", "departementName": "Nièvre" },
  { "regionKey": "hauts-de-france", "region": "Hauts-de-France", "departementNumber": "59", "departementName": "Nord" },
  { "regionKey": "hauts-de-france", "region": "Hauts-de-France", "departementNumber": "60", "departementName": "Oise" },
  { "regionKey": "normandie", "region": "Normandie", "departementNumber": "61", "departementName": "Orne" },
  { "regionKey": "hauts-de-france", "region": "Hauts-de-France", "departementNumber": "62", "departementName": "Pas-de-Calais" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "63", "departementName": "Puy-de-Dôme" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "64", "departementName": "Pyrénées-Atlantiques" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "65", "departementName": "Hautes-Pyrénées" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "66", "departementName": "Pyrénées-Orientales" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "67", "departementName": "Bas-Rhin" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "68", "departementName": "Haut-Rhin" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "69", "departementName": "Rhône" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "70", "departementName": "Haute-Saône" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "71", "departementName": "Saône-et-Loire" },
  { "regionKey": "pays-de-la-loire", "region": "Pays de la Loire", "departementNumber": "72", "departementName": "Sarthe" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "73", "departementName": "Savoie" },
  { "regionKey": "auvergne-rhone-alpes", "region": "Auvergne-Rhône-Alpes", "departementNumber": "74", "departementName": "Haute-Savoie" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "75", "departementName": "Paris" },
  { "regionKey": "normandie", "region": "Normandie", "departementNumber": "76", "departementName": "Seine-Maritime" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "77", "departementName": "Seine-et-Marne" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "78", "departementName": "Yvelines" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "79", "departementName": "Deux-Sèvres" },
  { "regionKey": "hauts-de-france", "region": "Hauts-de-France", "departementNumber": "80", "departementName": "Somme" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "81", "departementName": "Tarn" },
  { "regionKey": "occitanie", "region": "Occitanie", "departementNumber": "82", "departementName": "Tarn-et-Garonne" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "83", "departementName": "Var" },
  { "regionKey": "provence-alpes-cote-d-azur", "region": "Provence-Alpes-Côte d'Azur", "departementNumber": "84", "departementName": "Vaucluse" },
  { "regionKey": "pays-de-la-loire", "region": "Pays de la Loire", "departementNumber": "85", "departementName": "Vendée" },
  { "regionKey": "nouvelle-aquitaine", "region": "Nouvelle-Aquitaine", "departementNumber": "86", "departementName": "Vienne" },
  { "regionKey": "grand-est", "region": "Grand Est", "departementNumber": "88", "departementName": "Vosges" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "89", "departementName": "Yonne" },
  { "regionKey": "bourgogne-franche-comte", "region": "Bourgogne-Franche-Comté", "departementNumber": "90", "departementName": "Territoire de Belfort" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "91", "departementName": "Essonne" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "92", "departementName": "Hauts-de-Seine" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "93", "departementName": "Seine-Saint-Denis" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "94", "departementName": "Val-de-Marne" },
  { "regionKey": "ile-de-france", "region": "Île-de-France", "departementNumber": "95", "departementName": "Val-d'Oise" },
  { "regionKey": "corse", "region": "Corse", "departementNumber": "2A", "departementName": "Corse-du-Sud" },
  { "regionKey": "corse", "region": "Corse", "departementNumber": "2B", "departementName": "Haute-Corse" },
]


export const REGION_LOGOS = {
  "auvergne-rhone-alpes": require("../assets/images/regions/auvergne-rhone-alpes.png"),
  "bourgogne-franche-comte": require("../assets/images/regions/bourgogne-franche-comte.png"),
  "bretagne": require("../assets/images/regions/bretagne.png"),
  "centre-val-de-loire": require("../assets/images/regions/centre-val-de-loire.png"),
  "corse": require("../assets/images/regions/corse.png"),
  "grand-est": require("../assets/images/regions/grand-est.png"),
  "hauts-de-france": require("../assets/images/regions/hauts-de-france.png"),
  "ile-de-france": require("../assets/images/regions/ile-de-france.png"),
  "normandie": require("../assets/images/regions/normandie.png"),
  "nouvelle-aquitaine": require("../assets/images/regions/nouvelle-aquitaine.png"),
  "occitanie": require("../assets/images/regions/occitanie.png"),
  "pays-de-la-loire": require("../assets/images/regions/pays-de-la-loire.png"),
  "provence-alpes-cote-d-azur": require("../assets/images/regions/provence-alpes-cote-d-azur.png")
} as const

export type RegionKey = keyof typeof REGION_LOGOS;